const privacyData = [
  "Updating & Modifying your Data",
  "If you want an access to your personal data, or you want us to update, manage, export, or delete your information, please contact us at: office@intellrocket.com",
  "Data We Collect:",
  "IntellRocket collects and uses information such us:",
  "Your language & browser type,",
  "Time zone & location",
  "Operating system that you use,",
  "IP address,",
  "Access time and referring URLs;",
  "Unique device identifier,",
  "Unique cookie identifier.",
  "IntellRocket collects and uses your data in order to:",
  "share news about upcoming services and conduct marketing research and analysis where we are allowed by law to do so;",
  "keep records of communications;",
  "comply with legal obligations and fulfill government authorities’ request;",
  "assert, exercise or defend against legal claims,",
  "How We May Use It:",
  "IntellRocket will use your data to provide you better user experience and information relevant to you. We may send you marketing emails to inform you about news as well as launches of new services that may be of your interest. If you don’t want to receive those messages you can unsubscribe from our mailing list.",
  "Data Revelation",
  "If at any time we are obliged to disclose the collected data to a third party, based on a court decision and in accordance with the law, you will be notified in a timely manner, unless the court order contains a secrecy mark or a ban on notifying users.",
  "We won’t sell, show or give your data that we have collected through internet forms, email communication, FB pixel or Google Analytics to third parties. The collected data will not be published or misused in any way, nor used to identify individual visitors.",
  "IntellRocket may occasionally disclose some general information (e.g. the number of visitors of our website), but will never disclose confidential or identifiable information.",
  "Cookies",
  "IntellRocket uses “cookies” for limited purposes only. A “cookie” is a small piece of information that our website can send to your browser, which can then be stored on your hard drive. If you are concerned about your privacy, you can set your browser to notify you when you receive a cookie. You can also set your browser to reject cookies that our site tries to send you.",
  "Google and Facebook Pixel, create “cookies” that help IntellRocket monitor website traffic.",
  "Request for Services and Newsletter",
  "When signing up for one of our services as well as for our newsletter, you need to leave your email address. Your email address will be kept private, we will not give or sell it to third parties. You can unsubscribe from our Newsletter, any time – and we will automatically delete your email address from our database.",
  "Links to Third Party Websites",
  "IntellRocket may give links to third party websites, just as these websites may link to us. Other websites operate according to their terms of use and privacy policies. We have no control over those websites. We don’t own the information contained therein, don’t guarantee and are not responsible for any content, advertising, product or other material available on those websites.",
  "Social Networks",
  "We use social media to improve our mission. Using social network apps requires the use of third party services.",
  "For example, IntellRocket’s Facebook account is managed by Facebook and this account is accessed by Facebook users who have already accepted the Facebook Privacy Policy. Our Facebook page is managed by IntellRocket employees who are in charge of it. IntellRocket does not store the data of its followers or process data outside of Facebook.",
  "In addition to Facebook, other social networks we use are:",
  //   [
  //     { name: "Instagram", link: "https://www.instagram.com/intellrocket/" },
  //     { name: "Linkedin", link: "https://www.linkedin.com/company/intellrocket.com/" },
  //     { name: "Youtube", link: "https://www.youtube.com/channel/UCtiCaFY8kQj3SlR5pB8YETg" },
  //     { name: "Dribble", link: "https://dribbble.com/intellrocket/" },
  //   ],
  "Children",
  "We do not require any personal identification when it comes to children. Users under the age of 14 should not leave any personal information on the site.",
  "Data Security",
  "When you use our services, you are trusting us. We consider it a big privilege and responsibility and will work hard to protect your information. IntellRocket does everything in its power to store the data it uses and processes in secure conditions by storing it in a computer system that is protected by a password and to which only our employees have access.",
  "Privacy Policy Changes",
  "IntellRocket reserves the right to change this Privacy Policy at any time. If the change is more significant, (if it significantly affects your rights or changes the rules of data use), we will notify you via email in a timely manner.",
  "Questions",
  "We want to make our site as secure as possible. As your opinion is important to us, we invite you to provide us with your comments and suggestions on this Privacy Policy. If you have any questions regarding the Privacy Policy, feel free to contact us by email office@intellrocket.com.",
];
export default privacyData;
