const logoData = [
  {
    name: "reTyre",
    light: "/intellrocket-app/img/client-logos/reTyre-light.png",
    dark: "/intellrocket-app/img/client-logos/reTyre-dark.png",
    url: "https://www.retyre.co/",
  },
  {
    name: "interface masters",
    light: "/intellrocket-app/img/client-logos/imt-light.png",
    dark: "/intellrocket-app/img/client-logos/imt-dark.png",
    url: "https://interfacemasters.com/",
  },
  {
    name: "Inspirock",
    light: "/intellrocket-app/img/client-logos/inspirock-light.png",
    dark: "/intellrocket-app/img/client-logos/inspirock-dark.png",
    url: "https://www.inspirock.com/",
  },
  {
    name: "Niagara",
    light: "/intellrocket-app/img/client-logos/Niagara-light.png",
    dark: "/intellrocket-app/img/client-logos/Niagara-dark.png",
    url: "https://www.niagaranetworks.com/",
  },
  {
    name: "Alpha Parking",
    light: "/intellrocket-app/img/client-logos/alpha-parking-light.png",
    dark: "/intellrocket-app/img/client-logos/alpha-parking-dark.png",
    url: "https://alphaparking.de/",
  },
  {
    name: "Alucommerce",
    light: "/intellrocket-app/img/client-logos/alucommerce-light.png",
    dark: "/intellrocket-app/img/client-logos/alucommerce-light.png",
    url: "https://alucommerce.rs/en/",
  },
  {
    name: "Aspecto",
    light: "/intellrocket-app/img/client-logos/aspecto-light.png",
    dark: "/intellrocket-app/img/client-logos/aspecto-dark.png",
    url: "https://aspecto.ch/",
  },
  {
    name: "Kindernay",
    light: "/intellrocket-app/img/client-logos/kindernay-light.png",
    dark: "/intellrocket-app/img/client-logos/kindernay-dark.png",
    url: "https://kindernay.com/",
  },
  {
    name: "Bonex",
    light: "/intellrocket-app/img/client-logos/bonex-light.png",
    dark: "/intellrocket-app/img/client-logos/bonex-light.png",
    url: "https://bonexing.org/en/",
  },
  {
    name: "Inreact",
    light: "/intellrocket-app/img/client-logos/inreact-light.png",
    dark: "/intellrocket-app/img/client-logos/inreact-light.png",
    url: "https://inreact.worldsecuresystems.com/",
  },
  {
    name: "just-medical",
    light: "/intellrocket-app/img/client-logos/Just-Medical-light.png",
    dark: "/intellrocket-app/img/client-logos/Just-Medical-light.png",
    url: "https://www.just-medical.ch/",
  },
  {
    name: "recom",
    light: "/intellrocket-app/img/client-logos/recom.png",
    dark: "/intellrocket-app/img/client-logos/recom-dark.png",
    url: "http://www.recom.link/",
  },
  {
    name: "studio baza",
    light: "/intellrocket-app/img/client-logos/baza.png",
    dark: "/intellrocket-app/img/client-logos/baza-dark.png",
    url: "http://www.studiobaza.rs/",
  },
  {
    name: "Roche",
    light: "/intellrocket-app/img/client-logos/roche-light.png",
    dark: "/intellrocket-app/img/client-logos/roche-dark.png",
    url: "https://www.roche.com/",
  },
  {
    name: "Sintemma",
    light: "/intellrocket-app/img/client-logos/sintema.png",
    dark: "/intellrocket-app/img/client-logos/sintema-dark.png",
    url: "https://sintemma.com/",
  },
  {
    name: "smart visualizer",
    light: "/intellrocket-app/img/client-logos/Smart-Visualizer-light.png",
    dark: "/intellrocket-app/img/client-logos/Smart-Visualizer-dark.png",
    url: "https://www.svisualizer.com/#/login",
  },
  {
    name: "transportlog",
    light: "/intellrocket-app/img/client-logos/Transportlog-light.png",
    dark: "/intellrocket-app/img/client-logos/Transportlog-dark.png",
    url: "https://transportlog.org.rs/en/",
  },
  {
    name: "Vila Jugovo",
    light: "/intellrocket-app/img/client-logos/Vila-Jugovo-light.png",
    dark: "/intellrocket-app/img/client-logos/Vila-Jugovo-dark.png",
    url: "https://vilajugovos.rs/en/",
  },
  {
    name: "Vallis Technologies",
    light: "/intellrocket-app/img/client-logos/vallis-light.png",
    dark: "/intellrocket-app/img/client-logos/vallis-dark.png",
    url: "https://vallis-technologies.com/eng/",
  },
  {
    name: "Biologist",
    light: "/intellrocket-app/img/client-logos/Biologist-light.png",
    dark: "/intellrocket-app/img/client-logos/Biologist-dark.png",
    url: "https://biologist.rs/en/",
  },
  {
    name: "Profesional Medic",
    light: "/intellrocket-app/img/client-logos/profesional-medic-light.png",
    dark: "/intellrocket-app/img/client-logos/profesional-medic-light.png",
    url: "https://profesionalmedic.com/en/",
  },
];

export default logoData;
